# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb94e782e1fd2446d2082a3a3fb56a50e06cb795264a98a5a1088202ea9c53a3528a6f0512e319daad1f21b17254d9ee2cc3dc25f808606dcf00a1b5b5301e50
  amazon_associate_tag: <%= ENV["AMAZON_ASSOCIATE_TAG"] %>
  amazon_access_key: <%= ENV["AMAZON_ACCESS_KEY"] %>
  amazon_secret_key: <%= ENV["AMAZON_SECRET_KEY"] %>

test:
  secret_key_base: c6e4311374d14ae66e4f8c5b8289d29b07dd4a4397ef7cd2dd30db6ad116076f069528edc7c80e35eb693efaf3be645feebbf1402005622d07a5ec41fd37d30e
  amazon_associate_tag: <%= ENV["AMAZON_ASSOCIATE_TAG"] %>
  amazon_access_key: <%= ENV["AMAZON_ACCESS_KEY"] %>
  amazon_secret_key: <%= ENV["AMAZON_SECRET_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  amazon_associate_tag: <%= ENV["AMAZON_ASSOCIATE_TAG"] %>
  amazon_access_key: <%= ENV["AMAZON_ACCESS_KEY"] %>
  amazon_secret_key: <%= ENV["AMAZON_SECRET_KEY"] %>

